import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="m-0 p-0 box-border">
      <Head>
        <title>NFT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">Welcome to NFT Website</div>
    </div>
  );
}
